version: '3.5'

services:
  s_chat:
    build:
      # Builds from current directory
      context: .
      dockerfile: Dockerfile
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-9DAuFuuM6X77oC8HeZyqjGwKlkvPXPBiiR38iNIItYn/rPuKrAgrTroxLOHuct8n=}
      MIX_ENV: ${MIX_ENV:-dev}
      # Name of db service
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: chat_dev
      PGPORT: 5432
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: